Areas/Product/Controllers/ProductDiscountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagementsystem.Areas.Product.Controllers
{
    public class ProductDiscountController : Controller
    {
        private InventoryManagementContext db = new InventoryManagementContext();
        // GET: Product/ProductDiscount
        public ActionResult Index()
        {
            return View(db.ProductDiscounts.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ProductDiscount pd)
        {
            db.ProductDiscounts.Add(pd);
            db.SaveChanges();
            return RedirectToAction("Index");   
        }
        public ActionResult Details(int? id)
        {
            if (id != null)
            {
                ProductDiscount pd = db.ProductDiscounts.Find(id);             
                return View(pd);
            }
            return HttpNotFound();  
        }

        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                ProductDiscount pd = db.ProductDiscounts.Find(id);
                return View(pd);
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult Edit(ProductDiscount pd)
        {
            ProductDiscount existingrecord = db.ProductDiscounts.Find(pd.DiscountID);
            existingrecord.DiscountName = pd.DiscountName;
            existingrecord.Description = pd.Description;
            existingrecord.IsActive = pd.IsActive;
            existingrecord.DiscountPercent = pd.DiscountPercent;
            existingrecord.StartDate = pd.StartDate;
            existingrecord.EndDate = pd.EndDate;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                ProductDiscount pd = db.ProductDiscounts.Find(id);
                return View(pd);
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(ProductDiscount pd)
        {
            int? id = pd.DiscountID;
            if (id != null)
            {
                ProductDiscount foundProduct = db.ProductDiscounts.Find(id);
                db.ProductDiscounts.Remove(foundProduct);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return HttpNotFound();
        }
    }

 
}

Areas/Product/Views/ProductDiscount/Create.cshtml
@model InventoryManagementsystem.ProductDiscount
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create a new discount</h2>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.DiscountName, "Name", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DiscountName, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, "Description", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, "Active", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span>Yes</span> @Html.RadioButtonFor(model => model.IsActive, true) |
                <span>No</span> @Html.RadioButtonFor(model => model.IsActive, false)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiscountPercent, "Discount Percent", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DiscountPercent, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, "Start Date", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.StartDate, new { @type = "date", @class = "form-control datepicker" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, "EndDate", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EndDate, new { @type = "date", @class = "form-control datepicker" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

Areas/Product/Views/ProductDiscount/Delete.cshtml
@model InventoryManagementsystem.ProductDiscount
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete the discount</h2>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DiscountName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiscountName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @if (@Model.IsActive)
            {
                <span>Yes</span>
            }
            else
            {
                <span>No</span>
            }


        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiscountPercent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiscountPercent)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "ProductDiscount", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.DiscountID)
        <div class="form-actions">
            <input type="submit" value="Delete" class="btn btn-defaut"> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/Product/Views/ProductDiscount/Details.cshtml
@model InventoryManagementsystem.ProductDiscount
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Discount Details</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DiscountName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiscountName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @if (@Model.IsActive)
            {
                <span>Yes</span>
            }
            else
            {
                <span>No</span>
            }


        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiscountPercent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiscountPercent)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>


    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DiscountID })|
    @Html.ActionLink("Back to List", "Index")

</p>

Areas/Product/Views/ProductDiscount/Edit.cshtml
@model InventoryManagementsystem.ProductDiscount
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit the Discount</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model =>model.DiscountID)
<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(model => model.DiscountName, "Name", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.DiscountName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, "Description", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsActive, "Active", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <span>Yes</span> @Html.RadioButtonFor(model => model.IsActive, true) |
            <span>No</span> @Html.RadioButtonFor(model => model.IsActive, false)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DiscountPercent, "Discount Percent", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.DiscountPercent, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, "Start Date", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.StartDate, Model.StartDate.ToShortDateString(), new { @type = "date", @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, "EndDate", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.EndDate, Model.EndDate.ToShortDateString(), new { @type = "date", @class = "form-control " })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Update" class="btn btn-default" />
        </div>
    </div>

</div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

Areas/Product/Views/ProductDiscount/Index.cshtml
@model IEnumerable<InventoryManagementsystem.ProductDiscount>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New Discount", "Create")
</p>

<table class="container">
    <tr class="row">
        <th class="col p-3 ">
            @Html.DisplayNameFor(model => model.DiscountName)
        </th>
        <th class="col p-3 ">
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th class="col p-3 ">
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th class="col p-3 ">
            @Html.DisplayNameFor(model => model.DiscountPercent)
        </th>
        <th class="col p-3 ">
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th class="col p-3 ">
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th class="col p-3 ">
            @Html.DisplayName("Available actions")
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="row">
            <td class="col p-3 ">
                @Html.DisplayFor(modelItem => item.DiscountName)
            </td>
            <td class="col p-3 ">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td class="col p-3 ">
                @if (item.IsActive)
                {
                    <span>Yes</span>
                }
                else
                {
                    <span>No</span>
                }
            </td>
            <td class="col p-3 ">
                @Html.DisplayFor(modelItem => item.DiscountPercent)
            </td>
            <td class="col p-3 ">
                @Html.DisplayFor(modelItem => item.StartDate, item.StartDate.ToShortDateString())
            </td>
            <td class="col p-3 ">
                @Html.DisplayFor(modelItem => item.EndDate, item.EndDate.ToShortDateString())
            </td>

            <td class="col p-3 ">
                @Html.ActionLink("Edit", "Edit", new { id = item.DiscountID }) |
                @Html.ActionLink("Details", "Details", new { id = item.DiscountID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.DiscountID })
            </td>
        </tr>
    }


</table>