Areas/Product/Controllers/ProductInventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagementsystem.Areas.Product.Controllers
{

    public class ProductInventoryController : Controller
    {
        private InventoryManagementContext db = new InventoryManagementContext();
        // GET: Product/ProductInventory
        public ActionResult Index()
        {
            return View(db.Product_Inventory.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(Product_Inventory pi)
        {
            db.Product_Inventory.Add(pi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                Product_Inventory pi = db.Product_Inventory.Find(id);
                return View(pi);
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult Edit(Product_Inventory pi)
        {
            var ExistingRecord = db.Product_Inventory.Find(pi.ProductInventoryID);
            ExistingRecord.Name = pi.Name;
            ExistingRecord.Quantity = pi.Quantity;
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                Product_Inventory pi = db.Product_Inventory.Find(id);
                return View(pi);
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(Product_Inventory pi)
        {
            int? id = pi.ProductInventoryID;
            if (id != null)
            {
                Product_Inventory foundProduct = db.Product_Inventory.Find(id);
                db.Product_Inventory.Remove(foundProduct);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return HttpNotFound();
        }

        public ActionResult Details(int? id)
        {
            if (id != null)
            {
                Product_Inventory pi = db.Product_Inventory.Find(id);
                return View(pi);
            }
            return HttpNotFound();
        }
    }
}

Areas/Product/Views/ProductInventory/Create.cshtml
@model InventoryManagementsystem.Product_Inventory
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create a new Product Inventory</h2>


@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Name", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, "Quantity", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Quantity, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Product/Views/ProductInventory/Delete.cshtml
@model InventoryManagementsystem.Product_Inventory
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete the Product Inventory</h2>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "ProductInventory", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.ProductInventoryID)
        <div class="form-actions">
            <input type="submit" value="Delete" class="btn btn-defaut"> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/Product/Views/ProductInventory/Details.cshtml
@model InventoryManagementsystem.Product_Inventory
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductInventoryID })|
    @Html.ActionLink("Back to List", "Index")

</p>

Areas/Product/Views/ProductInventory/Edit.cshtml
@model InventoryManagementsystem.Product_Inventory
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit the Product Inventory</h2>


@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ProductInventoryID)
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Name", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, "Quantity", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Quantity, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>

    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Product/Views/ProductInventory/Index.cshtml
@model  IEnumerable<InventoryManagementsystem.Product_Inventory>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Product Inventory</h2>
<p>
    @Html.ActionLink("Create New Product Inventory", "Create")
</p>

<table class="container">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayName("Available actions")
</tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ProductInventoryID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ProductInventoryID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ProductInventoryID })
            </td>
        </tr>
    }


</table>