Areas/Product/Controllers/ProductManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PagedList;


namespace InventoryManagementsystem.Areas.Product.Controllers
{
    public class ProductManagerController : Controller
    {
        private InventoryManagementContext db = new InventoryManagementContext();
        // GET: Product/Product
        public ActionResult Index(int? page, string searchProduct, string searchByCategory, string sortOrder)
        {
            ViewBag.priceOrder = String.IsNullOrEmpty(sortOrder)?"price_desc":"";
            ViewBag.searchProduct = String.IsNullOrEmpty(searchProduct) ? "" : searchProduct;
            ViewBag.searchByCategory = String.IsNullOrEmpty(searchByCategory) ? "" : searchByCategory;


            IEnumerable<InventoryManagementsystem.Product> products = null;


            if (!String.IsNullOrEmpty(searchProduct)) {              
                products = db.Products
                            .Include(pc => pc.Product_Category)
                            .Include(pi => pi.Product_Inventory)
                            .Include(pd => pd.ProductDiscount)
                            .Where(p => p.Name.Contains(searchProduct))
                            .ToList();
            }
            else if (!String.IsNullOrEmpty(searchByCategory))
            {
                products = db.Products
                          .Include(pc => pc.Product_Category)
                          .Include(pi => pi.Product_Inventory)
                          .Include(pd => pd.ProductDiscount)
                          .Where(p => p.Product_Category.Name.Contains(searchByCategory))
                          .ToList();
            }
            else
            {
                products = db.Products
                           .Include(pc => pc.Product_Category)
                           .Include(pi => pi.Product_Inventory)
                           .Include(pd => pd.ProductDiscount)                           
                           .ToList();
            }

            switch (sortOrder)
            {
                case "price_desc":
                    products = products.OrderByDescending(p => p.Price);
                    break;
                default:
                    products =products.OrderBy(p => p.Price);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(products.ToPagedList(pageNumber,pageSize));
        }

        public ActionResult Create()
        {
             
            List<Product_Category> ListPC = db.Product_Category.ToList();            
            ViewBag.ListProductCategory = ListPC;

            List<Product_Inventory> ListPI = db.Product_Inventory.ToList();      
            ViewBag.ListProductInventory = ListPI;

            List<ProductDiscount> ListDis = db.ProductDiscounts.ToList();       
            ViewBag.ListProductDiscount = ListDis;

            return View();
        }

        [HttpPost]
        public ActionResult Create(InventoryManagementsystem.Product product)
        {
            db.Products.Add(product);  
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult Details(int? id)
        {
            if (id != null)
            {
                var product = db.Products
                            .Include(pc => pc.Product_Category)
                            .Include(pi => pi.Product_Inventory)
                            .Include(pd => pd.ProductDiscount)
                            .FirstOrDefault(pr=> pr.ProductID ==id);
                return View(product);
            }
            return HttpNotFound();
        }
       
        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                var product = db.Products.Find(id);
                List<Product_Category> ListPC = db.Product_Category.ToList();
                ViewBag.ListProductCategory = ListPC;

                List<Product_Inventory> ListPI = db.Product_Inventory.ToList();
                ViewBag.ListProductInventory = ListPI;

                List<ProductDiscount> ListDis = db.ProductDiscounts.ToList();
                ViewBag.ListProductDiscount = ListDis;
                return View(product);
            }
            return HttpNotFound();
        }
        [HttpPost]
        public ActionResult Edit(InventoryManagementsystem.Product product)
        {
            if (product != null)
            {
                var ExistingRecord = db.Products.Find(product.ProductID);
                ExistingRecord.Name = product.Name;
                ExistingRecord.Description = product.Description;
                ExistingRecord.SKU = product.SKU;
                ExistingRecord.CategoryID = product.CategoryID;
                ExistingRecord.InventoryID = product.InventoryID;
                ExistingRecord.Price = product.Price;
                ExistingRecord.DiscountID = product.DiscountID;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return HttpNotFound();
        }


        public ActionResult Delete(int? id) {
            if (id != null)
            {
                var product = db.Products
                          .Include(pc => pc.Product_Category)
                          .Include(pi => pi.Product_Inventory)
                          .Include(pd => pd.ProductDiscount)
                          .FirstOrDefault(pr => pr.ProductID == id);


                return View(product);
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(InventoryManagementsystem.Product product)
        {
            int? id = product.ProductID;
            if (product != null)
            {
                var foundProduct = db.Products.Find(id);
                if (foundProduct != null)
                {
                    db.Products.Remove(foundProduct);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return HttpNotFound();
        }
    }
}

Areas/Product/Views/ProductManager/Create.cshtml
@model InventoryManagementsystem.Product
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create a new Product</h2>


@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Name", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, "Description", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SKU, "SKU", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SKU, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "Category", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model =>model.CategoryID,
               new SelectList(ViewBag.ListProductCategory,"ProductCategoryID","Name"),
               "Select Category",
               new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InventoryID, "Inventory", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.InventoryID,
              new SelectList(ViewBag.ListProductInventory,"ProductInventoryID","Name"),
               "Select Inventory", 
               new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Price", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Price, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiscountID, "Discount", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model =>model.DiscountID,
                new SelectList(ViewBag.ListProductDiscount, "DiscountID", "DiscountName"),
               "Select Discount",
               new { @class = "form-control" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

Areas/Product/Views/ProductManager/Delete.cshtml
@model InventoryManagementsystem.Product
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h2>Do you want to delete this Product category</h2>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.SKU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SKU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Inventory.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Inventory.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDiscount.DiscountName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDiscount.DiscountName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDiscount.DiscountPercent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDiscount.DiscountPercent)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "ProductManager", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.ProductID)
        <div class="form-actions">
            <input type="submit" value="Delete" class="btn btn-defaut"> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/Product/Views/ProductManager/Details.cshtml
@model InventoryManagementsystem.Product
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details of the product</h2>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SKU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SKU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Inventory.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Inventory.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDiscount.DiscountName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDiscount.DiscountName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDiscount.DiscountPercent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDiscount.DiscountPercent)
        </dd>


    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model?.ProductID })|
    @Html.ActionLink("Back to List", "Index")

</p>

Areas/Product/Views/ProductManager/Edit.cshtml
@model InventoryManagementsystem.Product
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ProductID)
<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(model => model.Name, "Name", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, "Description", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SKU, "SKU", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.SKU, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryID, "Category", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CategoryID,
           new SelectList(ViewBag.ListProductCategory, "ProductCategoryID", "Name"),
           "Select Category",
           new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.InventoryID, "Inventory", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.InventoryID,
          new SelectList(ViewBag.ListProductInventory, "ProductInventoryID", "Name"),
           "Select Inventory",
           new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, "Price", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Price, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DiscountID, "Discount", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.DiscountID,
            new SelectList(ViewBag.ListProductDiscount, "DiscountID", "DiscountName"),
           "Select Discount",
           new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Update" class="btn btn-default" />
        </div>
    </div>

</div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Product/Views/ProductManager/Index.cshtml
@model PagedList.IPagedList<InventoryManagementsystem.Product>
@using PagedList.Mvc


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New Product", "Create")
</p>

@using (Html.BeginForm())
{
    <table>
    <tr>
        <th>@Html.DisplayName("Search by Product Name")</th>
        <td>@Html.TextBox("searchProduct")</td>
        <td> <input type="submit" value="Search" /></td>
       
        <th>@Html.DisplayName("Search by category")</th>
        <td>@Html.TextBox("searchByCategory")</td>
        <td> <input type="submit" value="Search" /></td>
    </tr>
    </table>
}

<br />
<table class="container">
    <tr class="row">
        <th class="col p-3 ">
            @Html.DisplayName("Product Name")
        </th>
        <th class="col p-3 ">
            @Html.DisplayName("Description")
        </th>
        <th class="col p-3 ">
            @Html.DisplayName("Category")
        </th>
        <th class="col p-3 ">
            @Html.DisplayName("Inventory")
        </th>
        <th class="col p-3 ">       
            @Html.ActionLink("Price (in $)","Index",
            new { sortOrder=ViewBag.priceOrder , searchByCategory=ViewBag.searchByCategory,
            searchProduct= ViewBag.searchProduct })
        </th>
        <th class="col p-3 ">
            @Html.DisplayName("Discount")
        </th>
        <th class="col p-3">
            @Html.DisplayName("Available actions")
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="row">
            <td class="col p-3 ">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td class="col p-3 ">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td class="col p-3 ">
                @Html.DisplayFor(modelItem => item.Product_Category.Name)
            </td>
            <td class="col p-3 ">
                @Html.DisplayFor(modelItem => item.Product_Inventory.Name)
            </td>
            <td class="col p-3 ">
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td class="col p-3 ">
                @Html.DisplayFor(modelItem => item.ProductDiscount.DiscountName)
            </td>

            <td class="col p-2 ">
                @Html.ActionLink("Edit", "Edit", new { id = item.ProductID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ProductID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ProductID })
            </td>
        </tr>
    }
</table>
<br />

Page @(Model.PageCount < Model.PageNumber ?0:Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page,sortOrder = ViewBag.priceOrder }), PagedListRenderOptions.ClassicPlusFirstAndLast)